/*
 *
 * Students constants
 *
 */

export const DEFAULT_ACTION = 'app/Students/DEFAULT_ACTION'

export const ADD_STUDENT_REQUEST = 'app/Students/ADD_STUDENT_REQUEST'
export const ADD_STUDENT_SUCCESS = 'app/Students/ADD_STUDENT_SUCCESS'
export const ADD_STUDENT_FAILURE = 'app/Students/ADD_STUDENT_FAILURE'

export const DELETE_STUDENT_REQUEST = 'app/Students/DELETE_STUDENT_REQUEST'
export const DELETE_STUDENT_SUCCESS = 'app/Students/DELETE_STUDENT_SUCCESS'
export const DELETE_STUDENT_FAILURE = 'app/Students/DELETE_STUDENT_FAILURE'

export const UPDATE_STUDENT_REQUEST = 'app/Students/UPDATE_STUDENT_REQUEST'
export const UPDATE_STUDENT_SUCCESS = 'app/Students/UPDATE_STUDENT_SUCCESS'
export const UPDATE_STUDENT_FAILURE = 'app/Students/UPDATE_STUDENT_FAILURE'

export const TOGGLE_STUDENT_PRESENCE_REQUEST =
  'app/Students/TOGGLE_STUDENT_PRESENCE_REQUEST'
export const TOGGLE_STUDENT_PRESENCE_SUCCESS =
  'app/Students/TOGGLE_STUDENT_PRESENCE_SUCCESS'
export const TOGGLE_STUDENT_PRESENCE_FAILURE =
  'app/Students/TOGGLE_STUDENT_PRESENCE_FAILURE'

export const TOGGLE_MODAL_REQUEST = 'app/Students/TOGGLE_MODAL_REQUEST'
export const TOGGLE_MODAL_SUCCESS = 'app/Students/TOGGLE_MODAL_SUCCESS'
export const TOGGLE_MODAL_FAILURE = 'app/Students/TOGGLE_MODAL_FAILURE'

export const TOGGLE_UPDATE_MODAL_REQUEST =
  'app/Students/TOGGLE_UPDATE_MODAL_REQUEST'
export const TOGGLE_UPDATE_MODAL_SUCCESS =
  'app/Students/TOGGLE_UPDATE_MODAL_SUCCESS'
export const TOGGLE_UPDATE_MODAL_FAILURE =
  'app/Students/TOGGLE_UPDATE_MODAL_FAILURE'
